/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utils.ValidateData;
import javax.swing.JOptionPane;

/**
 *
 * @author Linh
 */
public class frmlogin extends javax.swing.JFrame {

    /**
     * Creates new form frmlogin
     */
    public frmlogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(400,300);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_User = new javax.swing.JTextField();
        txt_matKhau = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        btn_quenMK = new javax.swing.JButton();
        btn_dangNhap = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Tên Đăng Nhập");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(32, 62, 89, 16);

        jLabel2.setText("Mật khẩu");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(32, 118, 52, 16);

        txt_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UserActionPerformed(evt);
            }
        });
        getContentPane().add(txt_User);
        txt_User.setBounds(180, 59, 154, 22);

        txt_matKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_matKhauActionPerformed(evt);
            }
        });
        getContentPane().add(txt_matKhau);
        txt_matKhau.setBounds(180, 115, 154, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 255));
        jLabel3.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 13, 143, 28);

        btn_quenMK.setBackground(new java.awt.Color(0, 153, 255));
        btn_quenMK.setForeground(new java.awt.Color(255, 255, 255));
        btn_quenMK.setText("Thoát");
        btn_quenMK.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N
        btn_quenMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quenMKActionPerformed(evt);
            }
        });
        getContentPane().add(btn_quenMK);
        btn_quenMK.setBounds(224, 164, 65, 25);

        btn_dangNhap.setBackground(new java.awt.Color(0, 153, 255));
        btn_dangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangNhap.setText("Đăng nhập");
        btn_dangNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 13), new java.awt.Color(0, 153, 255))); // NOI18N
        btn_dangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangNhapActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dangNhap);
        btn_dangNhap.setBounds(47, 164, 95, 25);

        jLabel4.setText("Quên mật khẩu?");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(196, 202, 93, 16);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 260, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UserActionPerformed

    private void btn_quenMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quenMKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_quenMKActionPerformed

    private void txt_matKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_matKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_matKhauActionPerformed
    static String nameLogin;
    static String maNVlogin;
    private void btn_dangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangNhapActionPerformed
        frmMain main = new frmMain();
        ValidateData validate = new ValidateData();
        frmNhanVien fNhanVien = new frmNhanVien();
        String user= txt_User.getText();
        if (user.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không được để trống!");
            return;
        }
        String pw = txt_matKhau.getText();
        if (pw.trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống!");
        }
        for (int i = 0; i < fNhanVien.listNV.size(); i++) {
            if (user.equalsIgnoreCase(fNhanVien.listNV.get(i).getMaNhanVien()) && validate.md5(pw).equals(fNhanVien.listNV.get(i).getMatKhau())) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                main.setVisible(true);
                nameLogin = fNhanVien.listNV.get(i).getHoTen();
                this.dispose();
                return;
            } else {
                JOptionPane.showMessageDialog(this, "Đăng nhập thất bại!");
                return;
            }
        }
    }//GEN-LAST:event_btn_dangNhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>    

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangNhap;
    private javax.swing.JButton btn_quenMK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txt_User;
    private javax.swing.JPasswordField txt_matKhau;
    // End of variables declaration//GEN-END:variables
}
