/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Linh
 */
import OBJ.KhachHang;
import Utils.ValidateData;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Linh
 */
public class frmKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form frmKhachHang
     */
    private DefaultTableModel defaultTableModel;
    KhachHang kh = new KhachHang();
    ArrayList<KhachHang> listKH = new ArrayList<>();
    ValidateData validate = new ValidateData();

    public frmKhachHang() {
        initComponents();
        loadFile();
        saveFile();
        getData(listKH);
    }

    public void loadFile() {
        try {
            BufferedReader br = null;
            FileReader fr = null;
            listKH = new ArrayList<>(); //lưu ý
            fr = new FileReader("khachHang.txt");
            br = new BufferedReader(fr);
            String s = null;

            try {
                while ((s = br.readLine()) != null) {
                    //Cắt chuỗi:
                    String arr[] = s.split("\t");
                    //Khởi tạo
                    KhachHang kh = new KhachHang();
                    kh.setMaKhachHang(arr[0]);
                    kh.setHoTen(arr[1]);
                    kh.setSoDienThoai(arr[2]);
                    kh.setEmail(arr[3]);
                    kh.setMatKhau(arr[4]);
                    kh.setGioiTinh(arr[5]);
                    kh.setNhom(Integer.parseInt(arr[6]));
                    kh.setTrangThai(Integer.parseInt(arr[7]));
                    listKH.add(kh);
                }
            } catch (IOException ex) {
                Logger.getLogger(frmKhachHang.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void saveFile() {

        try {
            BufferedWriter bw = null; //Khởi tạo
            FileWriter fw = null; //Khởi tạo
            String data = ""; //Tạo một string data bằng rỗng.
            for (int i = 0; i < listKH.size(); i++) {
                String row = ""; //tạo hàng rỗng
                row = row + listKH.get(i).getMaKhachHang() + "\t";
                row = row + listKH.get(i).getHoTen() + "\t";
                row = row + listKH.get(i).getSoDienThoai() + "\t";
                row = row + listKH.get(i).getEmail() + "\t";
                row = row + listKH.get(i).getMatKhau() + "\t";
                row = row + listKH.get(i).getGioiTinh() + "\t";
                row = row + listKH.get(i).getNhom() + "\t";
                row = row + listKH.get(i).getTrangThai() + "\n";
                data += row;
            }
            fw = new FileWriter("khachHang.txt");
            bw = new BufferedWriter(fw);
            bw.write(data);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(frmKhachHang.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void getData(ArrayList<KhachHang> listKH) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã KH");
        defaultTableModel.addColumn("Họ tên KH");
        defaultTableModel.addColumn("Số điện thoại");
        defaultTableModel.addColumn("Email ");
        defaultTableModel.addColumn("Giới tính ");
        defaultTableModel.addColumn("Nhóm");
        defaultTableModel.addColumn("Trạng thái");

        for (KhachHang obj : listKH) {
            Vector vector = new Vector();
            vector.add(obj.getMaKhachHang());
            vector.add(obj.getHoTen());
            vector.add(obj.getSoDienThoai());
            vector.add(obj.getEmail());
            vector.add(obj.getGioiTinh());
            vector.add(obj.getNhom() == 1 ? "Thường" : "Thân thiết");
            vector.add(obj.getTrangThai() == 1 ? "Hoạt động" : "Đã khóa");

            defaultTableModel.addRow(vector);
        }
        tbl_khachHang.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_khachHang = new javax.swing.JTable();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        pnl_thongTinKH = new javax.swing.JPanel();
        lb_maNV = new java.awt.Label();
        lb_email = new javax.swing.JLabel();
        lb_sdt = new javax.swing.JLabel();
        lb_nhom = new javax.swing.JLabel();
        lb_hoTen = new javax.swing.JLabel();
        lb_gioiTinh = new javax.swing.JLabel();
        lb_trangThai = new javax.swing.JLabel();
        txt_Sdt = new javax.swing.JTextField();
        txt_MaKH = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_ten = new javax.swing.JTextField();
        txt_gioiTinh = new javax.swing.JComboBox<>();
        txt_trangThai = new javax.swing.JComboBox<>();
        txt_nhom = new javax.swing.JComboBox<>();
        txt_matKhau = new javax.swing.JPasswordField();
        lb_email1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jPanel3.setPreferredSize(new java.awt.Dimension(877, 527));
        jPanel3.setLayout(null);

        tbl_khachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_khachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_khachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_khachHang);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(0, 303, 870, 230);

        btn_them.setText("Thêm");
        btn_them.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        jPanel3.add(btn_them);
        btn_them.setBounds(510, 167, 75, 31);

        btn_sua.setText("Sửa");
        btn_sua.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sua);
        btn_sua.setBounds(510, 205, 75, 31);

        btn_xoa.setText("Xóa");
        btn_xoa.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_xoa.setPreferredSize(new java.awt.Dimension(65, 25));
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        jPanel3.add(btn_xoa);
        btn_xoa.setBounds(650, 167, 75, 31);

        btn_thoat.setText("Thoát");
        btn_thoat.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.add(btn_thoat);
        btn_thoat.setBounds(650, 205, 75, 31);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("TÌM KIẾM"));

        btn_timKiem.setText("Tìm Kiếm");
        btn_timKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txt_timKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_timKiem))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_timKiem)
                    .addComponent(btn_timKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(482, 62, 342, 76);

        pnl_thongTinKH.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN NHÂN VIÊN"));

        lb_maNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_maNV.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_maNV.setText("Mã Khách Hàng");

        lb_email.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_email.setText("Email");

        lb_sdt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_sdt.setText("SĐT");

        lb_nhom.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_nhom.setText("Nhóm");

        lb_hoTen.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_hoTen.setText("Họ và Tên");

        lb_gioiTinh.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_gioiTinh.setText("Giới tính");

        lb_trangThai.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_trangThai.setText("Trạng thái");

        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });

        txt_ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenActionPerformed(evt);
            }
        });

        txt_gioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác", " " }));
        txt_gioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_gioiTinhActionPerformed(evt);
            }
        });

        txt_trangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Deactive" }));

        txt_nhom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thân thiết", "Mới", " " }));
        txt_nhom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nhomActionPerformed(evt);
            }
        });

        lb_email1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_email1.setText("Mật khẩu");

        javax.swing.GroupLayout pnl_thongTinKHLayout = new javax.swing.GroupLayout(pnl_thongTinKH);
        pnl_thongTinKH.setLayout(pnl_thongTinKHLayout);
        pnl_thongTinKHLayout.setHorizontalGroup(
            pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                            .addComponent(lb_nhom)
                            .addGap(55, 55, 55))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_thongTinKHLayout.createSequentialGroup()
                            .addComponent(lb_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                    .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                        .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_email)
                            .addComponent(lb_sdt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                        .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Sdt)
                            .addComponent(txt_nhom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(27, 27, 27))
                    .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                        .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_gioiTinh)
                    .addComponent(lb_trangThai)
                    .addComponent(lb_email1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_hoTen))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_ten)
                    .addComponent(txt_gioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_trangThai, 0, 104, Short.MAX_VALUE)
                    .addComponent(txt_matKhau))
                .addGap(26, 26, 26))
        );
        pnl_thongTinKHLayout.setVerticalGroup(
            pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lb_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                                .addComponent(lb_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_email1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(4, 4, 4))
                    .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(lb_email)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_Sdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_sdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb_gioiTinh)
                            .addComponent(txt_gioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_nhom)
                            .addComponent(txt_nhom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_trangThai)
                            .addComponent(txt_trangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel3.add(pnl_thongTinKH);
        pnl_thongTinKH.setBounds(1, 62, 474, 199);

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lima Fruits");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("QUẢN LÝ KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(116, 116, 116))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
        );

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 877, 44);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/giam-nguy-co-ung-thu-bang-quang-nho-an-nhieu-hoa-qua-1.jpg"))); // NOI18N
        jPanel3.add(jLabel1);
        jLabel1.setBounds(1, 36, 880, 490);

        add(jPanel3);
        jPanel3.setBounds(6, 3, 877, 527);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        String maKH = txt_MaKH.getText();
        if (maKH.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã khách hàng không được để trống!");
            return;
        }
        String hoTen = txt_ten.getText();
        if (hoTen.equals("")) {
            JOptionPane.showMessageDialog(this, "Họ tên không được để trống!");
            return;
        }
        String matKhau = txt_matKhau.getText();
        if (matKhau.equals("")) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống!");
            return;
        }
        String sdt = txt_Sdt.getText();
        if (sdt.length() == 0) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được trống!");
        }
        if ((sdt.length() != 10) && (sdt.charAt(0) != 0)) {
            JOptionPane.showMessageDialog(this, "Số điện thoại sai định dạng!");
            return;
        }
        String email = txt_Email.getText();
        if (!kiemTraEmail(email)) {
            JOptionPane.showMessageDialog(this, "Email sai định dạng!");
            return;
        }

        String gioiTinh = "Nam";
        if (txt_gioiTinh.getSelectedItem().equals("Nữ")) {
            gioiTinh = "Nữ";
        } else if (txt_gioiTinh.getSelectedItem().equals("Khác")) {
            gioiTinh = "Khác";
        }
        int trangThai = 0;
        if (txt_trangThai.getSelectedItem().equals("Active")) {
            trangThai = 1;
        }
        int nhom = 0;
        if (txt_nhom.getSelectedItem().equals("Mới")) {
            nhom = 1;
        }
        // Tạo đối tượng nhân viên
        KhachHang kh = new KhachHang();
        kh.setMaKhachHang(maKH);
        kh.setHoTen(hoTen);
        kh.setMatKhau(validate.md5(matKhau));
        kh.setSoDienThoai(sdt);
        kh.setEmail(email);
        kh.setGioiTinh(gioiTinh);
        kh.setTrangThai(trangThai);
        kh.setNhom(nhom);
        //Add kh vào listKH
        listKH.add(kh);
        //SaveFile
        saveFile();
        // Đổ dữ liệu lên bảng
        getData(listKH);
        JOptionPane.showMessageDialog(this, "Thêm thông tin thành công!");
        //Reset lại các ô nhập thông tin
        reset();
    }//GEN-LAST:event_btn_themActionPerformed
    public boolean kiemTraEmail(String email) {
        String dinhDangEmail = "^[_A-Za-z0-9-]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
        boolean ktEmail = email.matches(dinhDangEmail);
        return ktEmail;
    }
    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        String sdt = txt_Sdt.getText();
        if (sdt.length() == 0) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được trống!");
        } else {
            if ((sdt.length() != 10) && (sdt.charAt(0) != 0)) {
                JOptionPane.showMessageDialog(this, "Số điện thoại sai định dạng!");
                return;
            }
            String email = txt_Email.getText();
            if (!kiemTraEmail(email)) {
                JOptionPane.showMessageDialog(this, "Email sai định dạng!");
                return;
            }
            String hoTen = txt_ten.getText();
            if (hoTen.equals("")) {
                JOptionPane.showMessageDialog(this, "Họ tên không được để trống!");
                return;
            }
            String matKhau = txt_matKhau.getText();
            String gioiTinh = "Nam";
            if (txt_gioiTinh.getSelectedItem().equals("Nữ")) {
                gioiTinh = "Nữ";
            } else if (txt_gioiTinh.getSelectedItem().equals("Khác")) {
                gioiTinh = "Khác";
            }
            int trangThai = 0;
            if (txt_trangThai.getSelectedItem().equals("Active")) {
                trangThai = 1;
            }
            int nhom = 0;
            if (txt_nhom.getSelectedItem().equals("Quản lý")) {
                nhom = 1;
            }
            //Cập nhật khách hàng mới
            kh.setHoTen(hoTen);
            kh.setEmail(email);
            kh.setSoDienThoai(sdt);
            kh.setGioiTinh(gioiTinh);
            kh.setTrangThai(trangThai);
            kh.setNhom(nhom);
            //Set Arraylist
            listKH.set(index, kh);
            //Lưu file
            saveFile();
            //Cập nhật table
            getData(listKH);
            JOptionPane.showMessageDialog(this, "Chỉnh sửa khách hàng " + kh.getMaKhachHang() + " thành công!");
            //Reset form
            reset();
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        String tuKhoa = txt_timKiem.getText();
        if (tuKhoa.equals("")) {
            getData(listKH);
        } else {
            ArrayList<KhachHang> listKH_Search = new ArrayList<>();
            for (int i = 0; i < listKH.size(); i++) {
                if ((listKH.get(i).getHoTen().contains(tuKhoa)) || (listKH.get(i).getEmail().contains(tuKhoa)) || (listKH.get(i).getMaKhachHang().contains(tuKhoa))) {
                    listKH_Search.add(listKH.get(i));
                }
            }

            getData(listKH_Search);
            if (listKH_Search.size() == 0) {
                JOptionPane.showMessageDialog(this, "Khách hàng cần tìm không tồn tại!");
                reset();
                getData(listKH);
            }
        }
    }//GEN-LAST:event_btn_timKiemActionPerformed
    public void reset() {
        txt_MaKH.setText("");
        txt_ten.setText("");
        txt_matKhau.setText("");
        txt_Sdt.setText("");
        txt_Email.setText("");
        txt_timKiem.setText("");
    }
    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenActionPerformed

    private void txt_gioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_gioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_gioiTinhActionPerformed

    private void txt_nhomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nhomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nhomActionPerformed

    int index;
    private void tbl_khachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_khachHangMouseClicked
        btn_sua.setEnabled(true);
        btn_xoa.setEnabled(true);
        //Lay ra ban ghi
        int row = tbl_khachHang.getSelectedRow();
        String maKH = tbl_khachHang.getValueAt(row, 0).toString();
        for (int i = 0; i < listKH.size(); i++) {
            if (maKH.equals(listKH.get(i).getMaKhachHang())) {
                kh = listKH.get(i);
                index = i;
                break;
            }
        }

        txt_MaKH.setEnabled(false);
        txt_matKhau.setEnabled(false);
        btn_them.setEnabled(false);

        txt_MaKH.setText(kh.getMaKhachHang());
        txt_Email.setText(kh.getEmail());
        txt_Sdt.setText(kh.getSoDienThoai());
        txt_matKhau.setText(kh.getMatKhau());
        txt_ten.setText(kh.getHoTen());

        if (kh.getGioiTinh().equals("Nam")) {
            txt_gioiTinh.setSelectedItem("Nam");
        } else if (kh.getGioiTinh().equals("Nữ")) {
            txt_gioiTinh.setSelectedItem("Nữ");
        } else {
            txt_gioiTinh.setSelectedItem("Khác");
        }
        if (kh.getNhom() == 1) {
            txt_nhom.setSelectedItem("Thân thiết");
        } else {
            txt_nhom.setSelectedItem("Mới");
        }
        if (kh.getTrangThai() == 1) {
            txt_trangThai.setSelectedItem("Active");
        } else {
            txt_trangThai.setSelectedItem("Deactive");
        }
    }//GEN-LAST:event_tbl_khachHangMouseClicked

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        Integer confirm = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa khách hàng " + kh.getMaKhachHang() + " không?", "Xóa khách hàng.", 2);
        if (confirm == JOptionPane.YES_OPTION) {
            if (listKH.remove(kh) == true) {
                saveFile();
                getData(listKH);
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_email1;
    private javax.swing.JLabel lb_gioiTinh;
    private javax.swing.JLabel lb_hoTen;
    private java.awt.Label lb_maNV;
    private javax.swing.JLabel lb_nhom;
    private javax.swing.JLabel lb_sdt;
    private javax.swing.JLabel lb_trangThai;
    private javax.swing.JPanel pnl_thongTinKH;
    private javax.swing.JTable tbl_khachHang;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_Sdt;
    private javax.swing.JComboBox<String> txt_gioiTinh;
    private javax.swing.JPasswordField txt_matKhau;
    private javax.swing.JComboBox<String> txt_nhom;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timKiem;
    private javax.swing.JComboBox<String> txt_trangThai;
    // End of variables declaration//GEN-END:variables
}
