/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import OBJ.NhanVien;
import OBJ.SanPham;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Linh
 */
public class frmSanPham extends javax.swing.JPanel {

    /**
     * Creates new form frmSanPham
     */
    private DefaultTableModel defaultTableModel;
    SanPham sp = new SanPham();
    ArrayList<SanPham> listSP = new ArrayList<>();

    public frmSanPham() {
        initComponents();
        loadFile();
        getData(listSP);
    }

    public void loadFile() {
        try {
            BufferedReader br = null;
            FileReader fr = null;
            listSP = new ArrayList<>(); //lưu ý
            fr = new FileReader("sanPham.txt");
            br = new BufferedReader(fr);
            String s = null;

            try {
                while ((s = br.readLine()) != null) {
                    //Cắt chuỗi:
                    String arr[] = s.split("\t");
                    //Khởi tạo
                    SanPham sp = new SanPham();
                    sp.setMaSanPham(arr[0]);
                    sp.setTenSP(arr[1]);
                    sp.setTenNSX(arr[2]);
                    sp.setDonViTinh(arr[3]);
                    sp.setGiaNhap(arr[4]);
                    sp.setGiaBan(arr[5]);
                    sp.setSoLuong(arr[6]);
                    listSP.add(sp);
                }
            } catch (IOException ex) {
                Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void saveFile() {

        try {
            BufferedWriter bw = null; //Khởi tạo
            FileWriter fw = null; //Khởi tạo
            String data = ""; //Tạo một string data bằng rỗng.
            for (int i = 0; i < listSP.size(); i++) {
                String row = ""; //tạo hàng rỗng
                row = row + listSP.get(i).getMaSanPham() + "\t";
                row = row + listSP.get(i).getTenSP() + "\t";
                row = row + listSP.get(i).getTenNSX() + "\t";
                row = row + listSP.get(i).getDonViTinh() + "\t";
                row = row + listSP.get(i).getGiaNhap() + "\t";
                row = row + listSP.get(i).getGiaBan() + "\t";
                row = row + listSP.get(i).getSoLuong() + "\n";
                data += row;
            }
            fw = new FileWriter("sanPham.txt");
            bw = new BufferedWriter(fw);
            bw.write(data);
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(frmNhanVienTemplate.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void getData(ArrayList<SanPham> listSP) {
        defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Mã SP");
        defaultTableModel.addColumn("Tên SP");
        defaultTableModel.addColumn("Tên NSX");
        defaultTableModel.addColumn("Đơn vị tính");
        defaultTableModel.addColumn("Giá nhập");
        defaultTableModel.addColumn("Giá bán");
        defaultTableModel.addColumn("Số lượng");

        for (SanPham obj : listSP) {
            Vector vector = new Vector();
            vector.add(obj.getMaSanPham());
            vector.add(obj.getTenSP());
            vector.add(obj.getTenNSX());
            vector.add(obj.getDonViTinh());
            vector.add(obj.getGiaNhap());
            vector.add(obj.getGiaBan());
            vector.add(obj.getSoLuong());

            defaultTableModel.addRow(vector);
        }
        tbl_sanPham.setModel(defaultTableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_sanPham = new javax.swing.JTable();
        pnl_thongTinKH = new javax.swing.JPanel();
        lb_maNV = new java.awt.Label();
        lb_email = new javax.swing.JLabel();
        lb_sdt = new javax.swing.JLabel();
        lb_hoTen = new javax.swing.JLabel();
        txt_giaNhap = new javax.swing.JTextField();
        txt_MaSP = new javax.swing.JTextField();
        txt_donViTinh = new javax.swing.JTextField();
        txt_tenNSX = new javax.swing.JTextField();
        lb_email1 = new javax.swing.JLabel();
        txt_soLuong = new javax.swing.JTextField();
        lb_sdt1 = new javax.swing.JLabel();
        txt_giaBan = new javax.swing.JTextField();
        lb_sdt2 = new javax.swing.JLabel();
        txt_tenSP = new javax.swing.JTextField();
        btn_them = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txt_timKiem = new javax.swing.JTextField();
        btn_timKiem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(877, 527));
        setLayout(null);

        tbl_sanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_sanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_sanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_sanPham);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 323, 877, 206);

        pnl_thongTinKH.setBorder(javax.swing.BorderFactory.createTitledBorder("THÔNG TIN NHÂN VIÊN"));

        lb_maNV.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_maNV.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_maNV.setText("Mã Sản Phẩm");

        lb_email.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_email.setText("Đơn vị tính");

        lb_sdt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_sdt.setText("Giá nhập");

        lb_hoTen.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_hoTen.setText("Tên NSX");

        txt_MaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaSPActionPerformed(evt);
            }
        });

        txt_donViTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_donViTinhActionPerformed(evt);
            }
        });

        txt_tenNSX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenNSXActionPerformed(evt);
            }
        });

        lb_email1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_email1.setText("Tên SP");

        lb_sdt1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_sdt1.setText("Số lượng");

        txt_giaBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_giaBanActionPerformed(evt);
            }
        });

        lb_sdt2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lb_sdt2.setText("Giá bán");

        txt_tenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_thongTinKHLayout = new javax.swing.GroupLayout(pnl_thongTinKH);
        pnl_thongTinKH.setLayout(pnl_thongTinKHLayout);
        pnl_thongTinKHLayout.setHorizontalGroup(
            pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_email)
                    .addComponent(lb_sdt1)
                    .addComponent(lb_sdt)
                    .addComponent(lb_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                                .addComponent(txt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_email1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                                .addComponent(txt_donViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_hoTen))))
                    .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                                .addComponent(txt_giaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lb_sdt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        pnl_thongTinKHLayout.setVerticalGroup(
            pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_maNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lb_email1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_tenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_MaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnl_thongTinKHLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_donViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_hoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tenNSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_email))))
                .addGap(18, 18, 18)
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_giaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lb_sdt2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnl_thongTinKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_sdt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(pnl_thongTinKH);
        pnl_thongTinKH.setBounds(12, 80, 461, 210);

        btn_them.setText("Thêm");
        btn_them.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });
        add(btn_them);
        btn_them.setBounds(508, 185, 75, 31);

        btn_sua.setText("Sửa");
        btn_sua.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        add(btn_sua);
        btn_sua.setBounds(508, 223, 75, 31);

        btn_xoa.setText("Xóa");
        btn_xoa.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_xoa.setPreferredSize(new java.awt.Dimension(65, 25));
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });
        add(btn_xoa);
        btn_xoa.setBounds(648, 185, 75, 31);

        btn_thoat.setText("Thoát");
        btn_thoat.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        add(btn_thoat);
        btn_thoat.setBounds(648, 223, 75, 31);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("TÌM KIẾM"));

        btn_timKiem.setText("Tìm Kiếm");
        btn_timKiem.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btn_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txt_timKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_timKiem))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_timKiem)
                    .addComponent(btn_timKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        add(jPanel2);
        jPanel2.setBounds(480, 80, 342, 90);

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Lima Fruits");
        jLabel3.setToolTipText("");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("QUẢN LÝ SẢN PHẨM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 465, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(116, 116, 116))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel3)))
        );

        add(jPanel4);
        jPanel4.setBounds(0, 0, 877, 48);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/hinh-nen-trai-cay-dep-7.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(1, 46, 890, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_donViTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_donViTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_donViTinhActionPerformed

    private void txt_tenNSXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenNSXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenNSXActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
        String maSP = txt_MaSP.getText();
        if (maSP.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm không được để trống!");
            return;
        }
        String donVi = txt_donViTinh.getText();
        if (donVi.equals("")) {
            JOptionPane.showMessageDialog(this, "Đơn vị không được để trống!");
        }
        String tenSP = txt_tenSP.getText();
        if (tenSP.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được để trống!");
        }
        String tenNSX = txt_tenNSX.getText();
        if (tenNSX.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên NSX không được để trống!");
        }
        String giaNhap = txt_giaNhap.getText();
        if (giaNhap.equals("")) {
            JOptionPane.showMessageDialog(this, "Giá nhập không được để trống!");
        }
        String giaBan = txt_giaBan.getText();
        if (giaBan.equals("")) {
            JOptionPane.showMessageDialog(this, "Giá bán không được để trống!");
        }
        String soLuong = txt_soLuong.getText();
        if (soLuong.equals("")) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống!");
        }
        // Tạo đối tượng nhân viên
        SanPham sp = new SanPham();
        sp.setMaSanPham(maSP);
        sp.setTenSP(tenSP);
        sp.setTenNSX(tenNSX);
        sp.setDonViTinh(donVi);
        sp.setGiaNhap(giaNhap);
        sp.setGiaBan(giaBan);
        sp.setSoLuong(soLuong);
        //Add sp vào listSP
        listSP.add(sp);
        //SaveFile
        saveFile();
        // Đổ dữ liệu lên bảng
        getData(listSP);
        JOptionPane.showMessageDialog(this, "Thêm thông tin thành công!");
        //Reset lại các ô nhập thông tin
        reset();
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timKiemActionPerformed
        String tuKhoa = txt_timKiem.getText();
        if (tuKhoa.equals("")) {
            getData(listSP);
        } else {
            ArrayList<SanPham> listSP_Search = new ArrayList<>();
            for (int i = 0; i < listSP.size(); i++) {
                if ((listSP.get(i).getTenNSX().contains(tuKhoa)) || (listSP.get(i).getTenSP().contains(tuKhoa)) || (listSP.get(i).getMaSanPham().contains(tuKhoa))) {
                    listSP_Search.add(listSP.get(i));
                }
            }

            getData(listSP_Search);
            if (listSP_Search.size() == 0) {
                JOptionPane.showMessageDialog(this, "Sản phẩm cần tìm không tồn tại!");
                reset();
                getData(listSP);
            }
        }
    }//GEN-LAST:event_btn_timKiemActionPerformed

    private void txt_MaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaSPActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        String maSP = txt_MaSP.getText();
        if (maSP.equals("")) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm không được để trống!");
            return;
        }
        String donVi = txt_donViTinh.getText();
        if (donVi.equals("")) {
            JOptionPane.showMessageDialog(this, "Đơn vị không được để trống!");
            return;
        }
        String tenSP = txt_tenSP.getText();
        if (tenSP.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được để trống!");
            return;
        }
        String tenNSX = txt_tenNSX.getText();
        if (tenNSX.equals("")) {
            JOptionPane.showMessageDialog(this, "Tên NSX không được để trống!");
            return;
        }
        String giaNhap = txt_giaNhap.getText();
        if (giaNhap.equals("")) {
            JOptionPane.showMessageDialog(this, "Giá nhập không được để trống!");
            return;
        }
        String giaBan = txt_giaBan.getText();
        if (giaBan.equals("")) {
            JOptionPane.showMessageDialog(this, "Giá bán không được để trống!");
            return;
        }
        String soLuong = txt_soLuong.getText();
        if (soLuong.equals("")) {
            JOptionPane.showMessageDialog(this, "Số lượng không được để trống!");
            return;
        }
        sp.setMaSanPham(maSP);
        sp.setTenNSX(tenNSX);
        sp.setTenSP(tenSP);
        sp.setDonViTinh(donVi);
        sp.setGiaNhap(giaNhap);
        sp.setGiaBan(giaBan);
        sp.setSoLuong(soLuong);
        //Add sp vào listSP
        listSP.set(index, sp);
        //SaveFile
        saveFile();
        // Đổ dữ liệu lên bảng
        getData(listSP);
        JOptionPane.showMessageDialog(this, "Thêm thông tin thành công!");
        //Reset lại các ô nhập thông tin
        reset();
    }//GEN-LAST:event_btn_suaActionPerformed

    int index;
    private void tbl_sanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_sanPhamMouseClicked
        btn_sua.setEnabled(true);
        btn_xoa.setEnabled(true);
        // Lay ra ban ghi
        int row = tbl_sanPham.getSelectedRow();
        String maNV = tbl_sanPham.getValueAt(row, 0).toString();
        for (int i = 0; i < listSP.size(); i++) {
            if (maNV.equals(listSP.get(i).getMaSanPham())) {
                sp = listSP.get(i);
                index = i;
                break;
            }
        }

        txt_MaSP.setEnabled(false);
        btn_them.setEnabled(false);

        txt_MaSP.setText(sp.getMaSanPham());
        txt_donViTinh.setText(sp.getDonViTinh());
        txt_tenSP.setText(sp.getTenSP());
        txt_tenNSX.setText(sp.getTenNSX());
        txt_giaNhap.setText(sp.getGiaNhap());
        txt_giaBan.setText(sp.getGiaBan());
        txt_soLuong.setText(sp.getSoLuong());
    }//GEN-LAST:event_tbl_sanPhamMouseClicked


    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        Integer confirm = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa sản phẩm " + sp.getMaSanPham() + " không?", "Xóa sản phẩm.", 2);
        if (confirm == JOptionPane.YES_OPTION) {
            if (listSP.remove(sp) == true) {
                saveFile();
                getData(listSP);
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void txt_giaBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_giaBanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_giaBanActionPerformed

    private void txt_tenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenSPActionPerformed

    public void reset() {
        txt_MaSP.setText("");
        txt_tenSP.setText("");
        txt_tenNSX.setText("");
        txt_donViTinh.setText("");
        txt_giaNhap.setText("");
        txt_giaBan.setText("");
        txt_soLuong.setText("");
        txt_timKiem.setText("");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_timKiem;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_email;
    private javax.swing.JLabel lb_email1;
    private javax.swing.JLabel lb_hoTen;
    private java.awt.Label lb_maNV;
    private javax.swing.JLabel lb_sdt;
    private javax.swing.JLabel lb_sdt1;
    private javax.swing.JLabel lb_sdt2;
    private javax.swing.JPanel pnl_thongTinKH;
    private javax.swing.JTable tbl_sanPham;
    private javax.swing.JTextField txt_MaSP;
    private javax.swing.JTextField txt_donViTinh;
    private javax.swing.JTextField txt_giaBan;
    private javax.swing.JTextField txt_giaNhap;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JTextField txt_tenNSX;
    private javax.swing.JTextField txt_tenSP;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
